# ruff: noqa: E501  (prosa bilingue de la cronologia: partir las frases no las hace mas legibles)
"""Cronologia editorial de choques y reformas en America Latina, para el panel web.

No es un dato del laboratorio ni entra en ningun modelo: es contexto para leer las
series. Reglas con las que se escribio:

  - Solo hechos de fecha publica y conocida (el anio, y el mes cuando es parte del
    hecho: el corralito es de diciembre de 2001, no de 2001 a secas).
  - Ninguna cifra en el texto. La magnitud la pone la serie, que el lector ve al lado;
    escribirla aqui crearia un segundo numero que puede contradecir al primero.
  - Cada evento se contrasto con la serie del Banco Mundial antes de entrar: si la caida
    o el salto no se ve en su anio, el evento no entra (se descartaron el huracan Mitch
    en Honduras y la crisis bancaria de Paraguay de 1995 por eso).

Categorias: deuda, bancaria, hiperinflacion, cambiaria, reforma, externo, politica,
desastre. `iso3` puede ser "LATAM" para los choques regionales.
"""

from __future__ import annotations

EVENTOS: list[dict] = [
    dict(iso3="CRI", anio=1981, cat="deuda",
         es=("Costa Rica suspende el pago de su deuda externa",
             "Una de las primeras moratorias de la crisis de la deuda: el colón se devalúa y la economía cae en recesión hasta 1982."),
         en=("Costa Rica suspends external debt payments",
             "One of the first moratoria of the debt crisis: the colón is devalued and the economy stays in recession through 1982.")),
    dict(iso3="MEX", anio=1982, mes=8, cat="deuda",
         es=("México declara la moratoria: empieza la crisis de la deuda",
             "México anuncia que no puede pagar el servicio de su deuda externa. El crédito a la región se corta y comienza la «década perdida»."),
         en=("Mexico declares a moratorium: the debt crisis begins",
             "Mexico announces it cannot service its external debt. Credit to the region dries up and the \"lost decade\" begins.")),
    dict(iso3="CHL", anio=1982, cat="bancaria",
         es=("Crisis bancaria y devaluación en Chile",
             "Se abandona el tipo de cambio fijo, el PIB sufre su peor caída en décadas y a comienzos de 1983 el Estado interviene buena parte de la banca."),
         en=("Banking crisis and devaluation in Chile",
             "The fixed exchange rate is abandoned, output suffers its worst fall in decades, and in early 1983 the state takes over much of the banking system.")),
    dict(iso3="BOL", anio=1985, mes=8, cat="hiperinflacion",
         es=("Hiperinflación en Bolivia y el Decreto 21060",
             "La inflación llega a su pico en 1985; el decreto de agosto liberaliza precios y tipo de cambio y la frena en pocos meses."),
         en=("Hyperinflation in Bolivia and Decree 21060",
             "Inflation peaks in 1985; the August decree frees prices and the exchange rate and stops it within months.")),
    dict(iso3="NIC", anio=1988, cat="hiperinflacion",
         es=("Hiperinflación y guerra en Nicaragua",
             "A fines de los ochenta la guerra y el financiamiento monetario del déficit llevan a la hiperinflación y a una caída profunda del producto."),
         en=("Hyperinflation and war in Nicaragua",
             "In the late 1980s war and money-financed deficits lead to hyperinflation and a deep fall in output.")),
    dict(iso3="PAN", anio=1988, mes=3, cat="politica",
         es=("Sanciones de Estados Unidos y cierre de la banca en Panamá",
             "Las sanciones económicas y el cierre temporal de los bancos paralizan una economía dolarizada que depende de su centro financiero."),
         en=("US sanctions and bank closures in Panama",
             "Economic sanctions and the temporary closure of banks paralyse a dollarised economy that depends on its financial centre.")),
    dict(iso3="ARG", anio=1989, cat="hiperinflacion",
         es=("Hiperinflación en Argentina",
             "Los precios se descontrolan en 1989 y el gobierno entrega el poder de forma anticipada."),
         en=("Hyperinflation in Argentina",
             "Prices spiral out of control in 1989 and the government hands over power early.")),
    dict(iso3="PER", anio=1990, mes=8, cat="hiperinflacion",
         es=("Hiperinflación y «Fujishock» en Perú",
             "Tras dos años de hiperinflación, el ajuste de agosto de 1990 libera precios de golpe y abre la estabilización."),
         en=("Hyperinflation and the \"Fujishock\" in Peru",
             "After two years of hyperinflation, the August 1990 adjustment frees prices overnight and opens the way to stabilisation.")),
    dict(iso3="BRA", anio=1990, mes=3, cat="bancaria",
         es=("Plan Collor: el congelamiento de los depósitos en Brasil",
             "Para frenar la inflación, el gobierno congela por dieciocho meses buena parte de los depósitos bancarios: el antecedente regional del corralito."),
         en=("Collor Plan: Brazil freezes bank deposits",
             "To stop inflation, the government freezes most bank deposits for eighteen months: the region's precedent for the corralito.")),
    dict(iso3="CUB", anio=1991, cat="externo",
         es=("El «Período especial» en Cuba",
             "La disolución de la Unión Soviética corta el comercio y los subsidios de los que dependía la economía, que cae hasta 1993."),
         en=("Cuba's \"Special Period\"",
             "The dissolution of the Soviet Union cuts off the trade and subsidies the economy depended on, and output falls until 1993.")),
    dict(iso3="ARG", anio=1991, mes=4, cat="reforma",
         es=("Plan de Convertibilidad en Argentina",
             "Un peso igual a un dólar por ley: la inflación se desploma y la economía crece, a costa de quedar sin política cambiaria."),
         en=("Argentina's Convertibility Plan",
             "One peso equals one dollar by law: inflation collapses and the economy grows, at the cost of giving up exchange-rate policy.")),
    dict(iso3="BRA", anio=1994, mes=7, cat="reforma",
         es=("Plan Real en Brasil",
             "Una nueva moneda, el real, termina con décadas de inflación alta."),
         en=("Brazil's Real Plan",
             "A new currency, the real, ends decades of high inflation.")),
    dict(iso3="MEX", anio=1994, mes=12, cat="cambiaria",
         es=("«Efecto Tequila»: devaluación del peso mexicano",
             "La devaluación de diciembre desata una crisis financiera; la recesión de 1995 contagia a la región."),
         en=("The \"Tequila effect\": the Mexican peso is devalued",
             "December's devaluation sets off a financial crisis; the 1995 recession spreads to the region.")),
    dict(iso3="BRA", anio=1999, mes=1, cat="cambiaria",
         es=("Devaluación del real y paso a la flotación",
             "Tras la crisis rusa, Brasil abandona la banda cambiaria y deja flotar su moneda."),
         en=("The real is devalued and floated",
             "After the Russian crisis, Brazil abandons its exchange-rate band and lets its currency float.")),
    dict(iso3="ECU", anio=1999, mes=3, cat="bancaria",
         es=("Feriado bancario y congelamiento de depósitos en Ecuador",
             "Una crisis bancaria lleva al cierre de los bancos y al congelamiento de los depósitos; ese año el país deja de pagar su deuda."),
         en=("Bank holiday and deposit freeze in Ecuador",
             "A banking crisis leads to bank closures and a deposit freeze; that year the country defaults on its debt.")),
    dict(iso3="COL", anio=1999, cat="bancaria",
         es=("Crisis hipotecaria y primera recesión en décadas en Colombia",
             "El sistema UPAC colapsa con las tasas de interés y el país registra su primera contracción en más de medio siglo."),
         en=("Mortgage crisis and Colombia's first recession in decades",
             "The UPAC mortgage system collapses under high interest rates and the country records its first contraction in over half a century.")),
    dict(iso3="ECU", anio=2000, mes=1, cat="reforma",
         es=("Ecuador adopta el dólar",
             "Tras la crisis de 1999 se anuncia la dolarización: el sucre deja de existir."),
         en=("Ecuador adopts the dollar",
             "After the 1999 crisis, dollarisation is announced: the sucre ceases to exist.")),
    dict(iso3="SLV", anio=2001, mes=1, cat="reforma",
         es=("El Salvador adopta el dólar",
             "La Ley de Integración Monetaria hace del dólar la moneda de curso legal."),
         en=("El Salvador adopts the dollar",
             "The Monetary Integration Law makes the dollar legal tender.")),
    dict(iso3="ARG", anio=2001, mes=12, cat="bancaria",
         es=("Corralito, default y fin de la convertibilidad en Argentina",
             "En diciembre se restringen los retiros de depósitos (el «corralito») y el país declara el default; en enero de 2002 cae la convertibilidad y el peso se devalúa."),
         en=("Corralito, default and the end of convertibility in Argentina",
             "In December deposit withdrawals are restricted (the \"corralito\") and the country defaults; in January 2002 convertibility ends and the peso is devalued.")),
    dict(iso3="URY", anio=2002, cat="bancaria",
         es=("Crisis bancaria en Uruguay",
             "El contagio argentino provoca una corrida de depósitos y un feriado bancario."),
         en=("Banking crisis in Uruguay",
             "Contagion from Argentina triggers a run on deposits and a bank holiday.")),
    dict(iso3="VEN", anio=2002, mes=12, cat="politica",
         es=("Paro petrolero en Venezuela",
             "La huelga en la industria petrolera, de diciembre de 2002 a febrero de 2003, paraliza la principal fuente de divisas del país."),
         en=("Oil strike in Venezuela",
             "The oil-industry strike, from December 2002 to February 2003, paralyses the country's main source of foreign currency.")),
    dict(iso3="DOM", anio=2003, cat="bancaria",
         es=("Quiebra de Baninter y crisis bancaria en República Dominicana",
             "El fraude en uno de los mayores bancos del país desata una crisis bancaria y una fuerte devaluación."),
         en=("Baninter collapse and banking crisis in the Dominican Republic",
             "Fraud at one of the country's largest banks sets off a banking crisis and a sharp devaluation.")),
    dict(iso3="LATAM", anio=2009, cat="externo",
         es=("Crisis financiera global",
             "La quiebra de Lehman Brothers en septiembre de 2008 lleva a la recesión mundial de 2009, que alcanza a casi toda la región."),
         en=("Global financial crisis",
             "The collapse of Lehman Brothers in September 2008 leads to the world recession of 2009, which reaches almost the whole region.")),
    dict(iso3="HTI", anio=2010, mes=1, cat="desastre",
         es=("Terremoto en Haití",
             "El sismo de enero destruye buena parte de Puerto Príncipe."),
         en=("Earthquake in Haiti",
             "January's earthquake destroys much of Port-au-Prince.")),
    dict(iso3="LATAM", anio=2014, cat="externo",
         es=("Fin del auge de las materias primas",
             "Desde mediados de 2014 caen los precios del petróleo y de otras materias primas; Brasil entra en recesión en 2015 y 2016."),
         en=("The end of the commodity boom",
             "From mid-2014 the prices of oil and other commodities fall; Brazil enters recession in 2015 and 2016.")),
    dict(iso3="VEN", anio=2017, cat="hiperinflacion",
         es=("Hiperinflación y colapso de la producción en Venezuela",
             "Desde fines de 2017 la inflación se vuelve hiperinflación, en medio de una contracción de la economía sin precedentes en la región."),
         en=("Hyperinflation and output collapse in Venezuela",
             "From late 2017 inflation turns into hyperinflation, amid an economic contraction without precedent in the region.")),
    dict(iso3="ARG", anio=2018, mes=6, cat="cambiaria",
         es=("Crisis cambiaria y acuerdo con el FMI en Argentina",
             "El peso se desploma y el gobierno firma con el FMI el mayor préstamo de la historia del organismo."),
         en=("Currency crisis and IMF agreement in Argentina",
             "The peso collapses and the government signs the largest loan in the IMF's history.")),
    dict(iso3="NIC", anio=2018, mes=4, cat="politica",
         es=("Crisis política en Nicaragua",
             "Las protestas de abril y su represión llevan a la economía a una recesión."),
         en=("Political crisis in Nicaragua",
             "The April protests and their repression push the economy into recession.")),
    dict(iso3="LATAM", anio=2020, mes=3, cat="externo",
         es=("Pandemia de COVID-19",
             "Los confinamientos de 2020 provocan la mayor caída del producto regional en generaciones; el rebote llega en 2021."),
         en=("COVID-19 pandemic",
             "The 2020 lockdowns cause the region's largest fall in output in generations; the rebound comes in 2021.")),
    dict(iso3="CUB", anio=2021, mes=1, cat="reforma",
         es=("Unificación monetaria en Cuba",
             "La «Tarea Ordenamiento» elimina el peso convertible y unifica el tipo de cambio, con un salto de precios."),
         en=("Monetary unification in Cuba",
             "The \"Tarea Ordenamiento\" abolishes the convertible peso and unifies the exchange rate, with a jump in prices.")),
]

CATEGORIAS = {
    "deuda": ("Deuda y default", "Debt and default"),
    "bancaria": ("Crisis bancaria", "Banking crisis"),
    "hiperinflacion": ("Hiperinflación", "Hyperinflation"),
    "cambiaria": ("Crisis cambiaria", "Currency crisis"),
    "reforma": ("Reforma monetaria", "Monetary reform"),
    "externo": ("Choque externo", "External shock"),
    "politica": ("Crisis política", "Political crisis"),
    "desastre": ("Desastre natural", "Natural disaster"),
}
